export const BASE_APPLICATION_PRICE = 40_000;
export const ATTORNEY_CONSULTATION_FEE = 30_000;
export const ATTORNEY_TOTAL_PRICE =
  BASE_APPLICATION_PRICE + ATTORNEY_CONSULTATION_FEE;

// 特許庁印紙代
export const FIRST_CLASS_FEE = 12_000;
export const ADDITIONAL_CLASS_FEE = 8_800;

